### ISSUE TITLE
test, fix cs50.SQL

### ISSUE THREAD

**Issue by dmalan** [cs50/python-cs50#7]
Ideal to (re-)test SELECTs, INSERTs (with autoincrementing primary keys), UPDATEs, and DELETEs with:

* SQLite
* MySQL
* PostgreSQL

PostgreSQL, in particular, seems not to support [`lastrowid`](http://docs.sqlalchemy.org/en/latest/core/connections.html#sqlalchemy.engine.ResultProxy.lastrowid) (cf. http://stackoverflow.com/a/2189662), so I suspect this condition won't catch INSERTs in the same way:

```python
# if INSERT, return primary key value for a newly inserted row
elif result.lastrowid is not None:
    return result.lastrowid
```

Ergo the parenthetical comments:

```python
# if SELECT (or INSERT with RETURNING), return result set as list of dict objects
...
# if DELETE or UPDATE (or INSERT without RETURNING), return number of rows matched
```

Goal, then, is to test whether `execute` indeed behaves exactly as the comments and return values imply:

```python
# if SELECT (or INSERT with RETURNING), return result set as list of dict objects
if result.returns_rows:
    rows = result.fetchall()
    return [dict(row) for row in rows]

# if INSERT, return primary key value for a newly inserted row
elif result.lastrowid is not None:
    return result.lastrowid

# if DELETE or UPDATE (or INSERT without RETURNING), return number of rows matched
else:
    return result.rowcount
```

Seems reasonable, though, if user is user PostgreSQL, to expect them to use `RETURNING id` in order to get back INSERTs' autoincremented IDs, a la http://stackoverflow.com/a/8590931.

CC @glennholloway @brianyu28

**Comment by kzidane** [comment]
@dmalan, apologies for the delay!

[Tested](https://gist.github.com/kzidane/5cfe176218d282c97d2d5c4d6c48b41b) and seems to work as expected with SQLite. A couple of problems with MySQL and PostgreSQL though:

1. `lastrowid` seems to be set (not `None`), even in case of `DELETE`s or `UDPATE`s, causing `execute` to return `lastrowid`, while it should return `rowcount`. This happens with both back-ends.

2. as you said, user PostgreSQL may use `RETURNING id`, to get the ID of the last inserted row, but that, of course, is going to return a list.

```
$ python sqltests.py 
test_delete_returns_affected_rows (__main__.SQLiteTests) ... ok
test_insert_returns_last_row_id (__main__.SQLiteTests) ... ok
test_select_all (__main__.SQLiteTests) ... ok
test_select_cols (__main__.SQLiteTests) ... ok
test_select_where (__main__.SQLiteTests) ... ok
test_update_returns_affected_rows (__main__.SQLiteTests) ... ok
test_delete_returns_affected_rows (__main__.MySQLTests) ... FAIL
test_insert_returns_last_row_id (__main__.MySQLTests) ... ok
test_select_all (__main__.MySQLTests) ... ok
test_select_cols (__main__.MySQLTests) ... ok
test_select_where (__main__.MySQLTests) ... ok
test_update_returns_affected_rows (__main__.MySQLTests) ... FAIL
/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py:470: Warning: Unknown table 'cs50'
  cursor.execute(statement, parameters)
test_delete_returns_affected_rows (__main__.PostgresTests) ... FAIL
test_insert_returns_last_row_id (__main__.PostgresTests) ... ok
test_select_all (__main__.PostgresTests) ... ok
test_select_cols (__main__.PostgresTests) ... ok
test_select_where (__main__.PostgresTests) ... ok
test_update_returns_affected_rows (__main__.PostgresTests) ... FAIL

======================================================================
FAIL: test_delete_returns_affected_rows (__main__.MySQLTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "sqltests.py", line 14, in test_delete_returns_affected_rows
    self.assertEqual(self.db.execute("DELETE FROM cs50 WHERE id = :id", id=rows[0]["id"]), 1)
AssertionError: 0L != 1

======================================================================
FAIL: test_update_returns_affected_rows (__main__.MySQLTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "sqltests.py", line 68, in test_update_returns_affected_rows
    self.assertEqual(self.db.execute("UPDATE cs50 SET val = 'foo' WHERE id > 1"), 2)
AssertionError: 0L != 2

======================================================================
FAIL: test_delete_returns_affected_rows (__main__.PostgresTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "sqltests.py", line 14, in test_delete_returns_affected_rows
    self.assertEqual(self.db.execute("DELETE FROM cs50 WHERE id = :id", id=rows[0]["id"]), 1)
AssertionError: 0 != 1

======================================================================
FAIL: test_update_returns_affected_rows (__main__.PostgresTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "sqltests.py", line 68, in test_update_returns_affected_rows
    self.assertEqual(self.db.execute("UPDATE cs50 SET val = 'foo' WHERE id > 1"), 2)
AssertionError: 0 != 2

----------------------------------------------------------------------
Ran 18 tests in 7.126s

FAILED (failures=4)
```

**Comment by razvan-tache** [comment]
Hi,
I'm trying to implement "CS50 Finance", and I can confirm the issue of updating.
It seems that lastrowid is 0 on update.

Running the following script with sqlite3 will provide the following dump: 
![screenshot sqlite](https://cloud.githubusercontent.com/assets/2325263/25632389/1cac039a-2f7c-11e7-9fc6-31571bdd1d07.png)

```python
import sqlalchemy

engine = sqlalchemy.create_engine("sqllite:///finance.db")
result = engine.execute("UPDATE users SET cash = 10000 WHERE id = 1")

dump(result)
```

Dump attached
[ResultDump.pdf](https://github.com/cs50/python-cs50/files/971560/ResultDump.pdf)

**Comment by dmalan** [comment]
@razvan-tache, thanks for this report. Want to try this latest branch, https://github.com/cs50/python-cs50/tree/postgresql?
