### ISSUE TITLE
deprecation warning about werkzeug in new IDE

### ISSUE THREAD

**Issue by curiouskiwi** [cs50/python-cs50#77]
in new IDE, some users getting a deprecation warning about werkzeug

```INFO:werkzeug:192.168.250.119 - - [27/Jun/2019 12:27:42] "GET / HTTP/1.0" 500 -

ERROR:werkzeug:Error on request:

Traceback (most recent call last):

File "/opt/pyenv/versions/3.7.2/lib/python3.7/site-packages/werkzeug/serving.py", line 302, in run_wsgi

execute(self.server.app)

File "/opt/pyenv/versions/3.7.2/lib/python3.7/site-packages/werkzeug/serving.py", line 290, in execute

application_iter = app(environ, start_response)

File "/home/ubuntu/environment/project/application.py", line 24, in <module>

app = Flask(__name__)

File "/opt/pyenv/versions/3.7.2/lib/python3.7/site-packages/cs50/flask.py", line 32, in after

self.wsgi_app = ProxyFix(self.wsgi_app)

File "/opt/pyenv/versions/3.7.2/lib/python3.7/site-packages/werkzeug/contrib/fixers.py", line 141, in __init__

stacklevel=2,

DeprecationWarning: 'werkzeug.contrib.fixers.ProxyFix' has moved to 'werkzeug.middleware.proxy_fix.ProxyFix'. This import is deprecated as of version 0.15 and will be removed in 1.0.```

**Comment by curiouskiwi** [comment]
@kzidane as requested

**Comment by curiouskiwi** [comment]
To followup, this appears to happen if you have

    from cs50 import SQL
    db = SQL("sqlite:///name.db")

in two different files. 

In the example I had, this was in application.py and in an imported helpers.py.

Removing it from helpers.py solved the problem.

**Comment by dmalan** [comment]
@kzidane since ide.cs50.io now uses HTTPS for students' apps on `cs50.xyz`, I imagine we can remove https://github.com/cs50/python-cs50/blob/develop/src/cs50/flask.py#L23-L35 altogether now?

**Comment by dmalan** [comment]
Fixed by https://github.com/cs50/python-cs50/commit/010b59e0dd213c70ea5f4b6e24acb1c23d6e800b.
